MOCK_EXTRA_HEADERS = {'user-agent': 'Digital Home / Samsung SM-G991B / Android 14', 'client': 'dotcom_xfinity', 'client-detail': 'MOBILE;Samsung;SM-G991B;Android 14;v5.38.0', 'accept-language': 'en-US'}
MOCK_OAUTH_PROXY = None
MOCK_OAUTH_CERT_VERIFY = False
MOCK_REQUESTS_TIMEOUT = 90
MOCK_USAGE_URL = 'https://csp-pci-prod.codebig2.net/selfhelp/account/me/services/internet/usage?filter=internet'


MOCK_USAGE_RESPONSE_SUCCESS = {
        'accountNumber': '8772105840115998', 
        'courtesyUsed': 0, 
        'courtesyRemaining': 1, 
        'courtesyAllowed': 1, 
        'courtesyMonths': ['03/2023'], 
        'inPaidOverage': False, 
        'displayUsage': True, 
        "usageMonths": [
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '10/01/2024', 'endDate': '10/31/2024', 'homeUsage': 691, 'wifiUsage': 0, 'totalUsage': 691, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '11/01/2024', 'endDate': '11/30/2024', 'homeUsage': 870, 'wifiUsage': 0, 'totalUsage': 870, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '12/01/2024', 'endDate': '12/31/2024', 'homeUsage': 1007, 'wifiUsage': 0, 'totalUsage': 1007, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '01/01/2025', 'endDate': '01/31/2025', 'homeUsage': 1023, 'wifiUsage': 0, 'totalUsage': 1023, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '02/01/2025', 'endDate': '02/28/2025', 'homeUsage': 858, 'wifiUsage': 0, 'totalUsage': 858, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '03/01/2025', 'endDate': '03/31/2025', 'homeUsage': 848, 'wifiUsage': 0, 'totalUsage': 848, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '04/01/2025', 'endDate': '04/30/2025', 'homeUsage': 677, 'wifiUsage': 0, 'totalUsage': 677, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '05/01/2025', 'endDate': '05/31/2025', 'homeUsage': 903, 'wifiUsage': 0, 'totalUsage': 903, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '06/01/2025', 'endDate': '06/30/2025', 'homeUsage': 864, 'wifiUsage': 0, 'totalUsage': 864, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '07/01/2025', 'endDate': '07/31/2025', 'homeUsage': 820, 'wifiUsage': 0, 'totalUsage': 820, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '08/01/2025', 'endDate': '08/31/2025', 'homeUsage': 762, 'wifiUsage': 0, 'totalUsage': 762, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
            {'policyName': '1.2 Terabyte Data Plan', 'startDate': '09/01/2025', 'endDate': '09/30/2025', 'homeUsage': 324, 'wifiUsage': 0, 'totalUsage': 324, 'allowableUsage': 1229, 'unitOfMeasure': 'GB', 'displayUsage': True, 'devices': [{...}], 'additionalBlocksUsed': 0, 'additionalCostPerBlock': 10, 'additionalUnitsPerBlock': 50, 'additionalBlockSize': 50, 'additionalIncluded': 0, 'additionalUsed': 0, 'additionalPercentUsed': 0.0, 'additionalRemaining': 0, 'billableOverage': 0, 'overageCharges': 0.0, 'overageUsed': 0, 'currentCreditAmount': 0, 'maxCreditAmount': 0, 'maximumOverageCharge': 100, 'policy': 'limited'},
        ],
    }


MOCK_PLAN_RESPONSE_SUCCESS = {
    'tier': {
        'uploadSpeed': 35.0, 
        'downloadSpeed': 800.0, 
        'productNumber': '20300456', 
        'tierOfService': 'XI Superfast'
        }
    }
