services:
  xfinity:
    image: ghcr.io/thor0215/hassio-xfinity-usage-amd64:latest
    container_name: xfinity
    entrypoint: /bin/sh -c "python3 -Wignore /xfinity_usage_addon.py"
    restart: unless-stopped
    environment:
      TZ: America/Chicago
      BYPASS: 1
      MQTT_SERVICE: true
      MQTT_HOST: 
      MQTT_PORT: 1883
      MQTT_USERNAME: 
      MQTT_PASSWORD: 
      MQTT_RAW_USAGE: false
      LOG_LEVEL: info
      POLLING_RATE: 3600
    volumes:
      - ../config:/config
    shm_size: 1gb
  